### PR TITLE
Revise transform calling convention in presence of capture

### LINKED ISSUE #9: Sugar syntax for complex assoc?
Hi! Your library is great!

Just an idea:
```clojure
(transform big-map
  [:votes *] #(assoc %1 :votes (count (:voters %1)))
  [:votes *] #(assoc %1 :did-vote (contains? (:voters %1) "74.125.232.96")))
```
could also be expressed like this:
```clojure
(transform big-map
  [:votes #> * :votes]    #(count (:voters %))
  [:votes #> * :did-vote] #(contains? (:voters %) "74.125.232.96"))
```
where a reader tag (or better) tells at what level the assoc fn applies. (Tells where % will be.).

Or maybe you already thought of something similar to what you did with `dissoc`?

Congrats for your excellent work!

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes #9

### CODE REVIEW

**Comment by boxed** [comment]
Sweet!

**Comment by crisptrutski** [comment]
Should I cut a release?

**Comment by boxed** [comment]
Maybe we should wait for @leontalbot to say he's totally happy? But then absolutely. I'm quite happy with this!

**Comment by boxed** [comment]
Then a release would be great! :P

**Comment by crisptrutski** [comment]
Kraken has been released

**Pull request merged**
