### PR TITLE
Capture groups

### LINKED ISSUE #9: Sugar syntax for complex assoc?
Hi! Your library is great!

Just an idea:
```clojure
(transform big-map
  [:votes *] #(assoc %1 :votes (count (:voters %1)))
  [:votes *] #(assoc %1 :did-vote (contains? (:voters %1) "74.125.232.96")))
```
could also be expressed like this:
```clojure
(transform big-map
  [:votes #> * :votes]    #(count (:voters %))
  [:votes #> * :did-vote] #(contains? (:voters %) "74.125.232.96"))
```
where a reader tag (or better) tells at what level the assoc fn applies. (Tells where % will be.).

Or maybe you already thought of something similar to what you did with `dissoc`?

Congrats for your excellent work!

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes #9

### CODE REVIEW

**Comment by crisptrutski** [comment]
Refactored to satisfy notes above (oops, deleted to remove from merge commit message, but see rationale in latest commit)

Midje and README tests still out of date, just polishing that up now

**Comment by crisptrutski** [comment]
@boxed IMHO ready for merge, let me know what you think

**Comment by boxed** [comment]
Great! Maybe the tests for %% and %> should more clearly show how they differ though. But that's a minor thing really. Merge away!

**Comment by boxed** [comment]
Oh yea.. we should look at the README file too. It is getting a bit out of date. For example the big example at the end should probably be removed and some nice examples of the capture feature added.

**Comment by crisptrutski** [comment]
Took a stab at README, will merge once passing ('works locally', but failing on Travis, will look now)

Leaving other README updates to you as I'm out of spare time for this weekend :money_with_wings: 

One comment on tests: sharing cases between CLJ and CLJS would make things much easier, thinking maybe all the source data and expectations could be in a third namespace as a start - would be so much easier to keep them in sync.

Now that `cljs.test` has landed another option is just to go back to more vanilla testing so that the entire namespace can be shared.

Also re: README tests, do you know a way to get those run again when using `lein midje :autowatch`? Pet hate right now!

**Comment by boxed** [comment]
Re tests not re-running properly: Heh, well I guess that's my fault too since I'm the author of midje-readme :P

Pity midje doesn't do clojurescript. I Agree it's probably better to bite down and accept worse test feedback and uglier test code for this project :( :(

**Comment by crisptrutski** [comment]
OK, maybe I'll dig into it and send a PR to your other repo next week then ;)

RE: the ugly output, I find https://github.com/pjstadig/humane-test-output helps a lot, although probably needs a fork to work with clojurescript (haven't looked if that's happened yet).

ClojureScript seems to be picking up more steam recently, maybe Midje will make the jump over? Just sharing input/output data between tests should really be enough to stay sane for the scope of this library.

Maybe something like:

```clojure
(def expand-path-cases [[description data path], ...]
(def transform-cases [[description data transform-pairs output], ...]
...
```

**Comment by boxed** [comment]
Well it'd be nice to run all tests on both clj and cljs (maybe even clojure.net or whatever eventually)

**Comment by boxed** [comment]
Anyway, great job on this!

**Comment by boxed** [comment]
I updated the example at the bottom of the readme to use this new feature. I like it!

**Comment by boxed** [comment]
Well it's not that bad. #(keys %2) will do but yea.

**Comment by crisptrutski** [comment]
Yeah, no release cut so plenty of time to change it ;)

My intuition is that the "not interested in last crumb's value" case is common enough that we should call with just the captures as @leontalbot suggests. Prime case - using existing data to create a brand new leaf.

While it feels a bit surprising to me to change the first argument when a capture is introduced, in cases where that value is needed.. you can simply capture it explicitly.

Reopend https://github.com/boxed/instar/issues/9 to track this

**Pull request merged**
